name: redo_boilerplate
description: CLI to scaffold Flutter boilerplate (themes, dependencies, folders)
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.7.0
  prompts: ^2.0.0
  path: ^1.9.1
  yaml_edit: ^2.2.2
  mustache_template: ^2.0.0
  io: ^1.0.5
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^6.0.0

repository: https://github.com/aasiskrk/Redo-Boilerplate
issue_tracker: https://github.com/aasiskrk/Redo-Boilerplate/issues
homepage: https://github.com/aasiskrk/Redo_Boilerplate

executables:
  boiler: boiler
  redo_boiler: redo_boiler



